apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-5-dev

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-api-ingress.yaml
  - argocd-ingress.yaml 
images:
  - name: dokkaushik/angular-app-5
    newName: docker.io/dokkaushik/angular-app-5
    newTag: bd81fefe77b726d0c2dc8320c154ae098adc62b9

  - name: dokkaushik/dotnet-app-5
    newName: docker.io/dokkaushik/dotnet-app-5
    newTag: bd81fefe77b726d0c2dc8320c154ae098adc62b9
