apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-5-dev

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-api-ingress.yaml
  - argocd-ingress.yaml 
images:
  - name: dokkaushik/angular-app-5
    newName: docker.io/dokkaushik/angular-app-5
    newTag: 95a6c09ed543cdc8dc7de083ecfdbb8c01f9b413

  - name: dokkaushik/dotnet-app-5
    newName: docker.io/dokkaushik/dotnet-app-5
    newTag: 95a6c09ed543cdc8dc7de083ecfdbb8c01f9b413
