apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-5-dev

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-api-ingress.yaml
  - argocd-ingress.yaml 
images:
  - name: dokkaushik/angular-app-5
    newName: docker.io/dokkaushik/angular-app-5
    newTag: 20d79318e5bd6889b1af6358e2ed8e6445513918

  - name: dokkaushik/dotnet-app-5
    newName: docker.io/dokkaushik/dotnet-app-5
    newTag: 20d79318e5bd6889b1af6358e2ed8e6445513918
